services:
  nginx:
    image: vvooki/moja-aplikacja-nginx:latest
    container_name: nginx
    ports:
      - "8082:80"
    depends_on:
      - php
    networks:
      - backend

  php:
    image: vvooki/moja-aplikacja-php:latest
    container_name: php
    networks:
      - backend

  db:
    image: vvooki/moja-aplikacja-sql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

networks:
  backend:
    name: app-network
    driver: bridge
